/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import form_pacijent.FormNoviPacijent;
import form_pacijent.FormPretragaPacijenta;
import controller.ClientController;
import domain.Pacijent;
import domain.StavkaTermina;
import domain.Termin;
import domain.Usluga;
import domain.Zaposleni;
import form_termin.FormPretragaTermina;
import form_usluga.FormNovaUsluga;
import form_usluga.FormPretragaUsluge;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import models.TableModelStavkeTermina;
import session.Session;

/**
 *
 * @author Ivana
 */
public class MainForm extends javax.swing.JFrame {

    private Zaposleni ulogovani;
    private double iznosBezPopusta;
    private double popust;
    private Pacijent pacijent;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        Session.getInstance().setMf(this);
        lblUlogovani.setText("Ulogovani zaposleni: " + ulogovani);
        setTitle("Klijentska forma");
        txtUkupanIznos.setEditable(false);
        txtPopust.setEditable(false);
        txtIznosBezPopusta.setEditable(false);
        popuniUsluge();
        popuniPacijente();
        tblStavke.setModel(new TableModelStavkeTermina());
        
        JButton[] manjaDugmad = {btnDodajStavku, btnObrisiStavku};
        for (JButton btn : manjaDugmad) {
        btn.setBackground(Color.WHITE); // bela pozadina
        btn.setForeground(new Color(80, 150, 230)); 
            btn.setFocusPainted(false);
            btn.setFont(new Font("Segoe UI", Font.BOLD, 13));
            btn.setBorder(BorderFactory.createCompoundBorder(
                    new LineBorder(new Color(180, 220, 250), 1, true),
                    new EmptyBorder(4, 10, 4, 10) // manji padding
            ));
        }       
        
        btnSacuvaj.setBackground(new Color(100, 170, 255)); 
        btnSacuvaj.setForeground(Color.WHITE);
        btnSacuvaj.setFocusPainted(false);
        btnSacuvaj.setFont(new Font("Segoe UI", Font.BOLD, 15));
        btnSacuvaj.setBorder(BorderFactory.createCompoundBorder(
                new LineBorder(new Color(80, 150, 230), 1, true),
                new EmptyBorder(8, 20, 8, 20) 
        ));
        

        cmbUsluga.setBackground(Color.WHITE);
        cmbUsluga.setForeground(Color.BLACK);
        cmbUsluga.setBorder(BorderFactory.createLineBorder(new Color(180, 220, 250), 1, true));

        
        models.TableStyle.applyTableStyle(tblStavke);
        
       
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                        null,
                        "Da li ste sigurni da zelite da se odjavite?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION
                );

                if (response == JOptionPane.YES_OPTION) {
                    try {
                        ClientController.getInstance().logout(ulogovani);
                        System.exit(0);
                    } catch (Exception ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbUsluga = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPacijent = new javax.swing.JComboBox();
        txtDatumVreme = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        txtIznosBezPopusta = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        txtUkupanIznos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviPacijent = new javax.swing.JMenuItem();
        miPretragaPacijenta = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miNovaUsluga = new javax.swing.JMenuItem();
        miPretragaUsluge = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miPretragaTermina = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Termin"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke termina"));

        jLabel5.setText("Usluga:");

        jLabel7.setText("Napomena:");

        cmbUsluga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obriši stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblStavke);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(cmbUsluga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiStavku)
                    .addComponent(btnDodajStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("Pacijent:");

        jLabel2.setText("Datum i vreme:");

        jLabel3.setText("Opis:");

        jLabel4.setText("Iznos bez popusta:");

        cmbPacijent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPacijent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPacijentItemStateChanged(evt);
            }
        });

        txtDatumVreme.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm"))));
        txtDatumVreme.setText("06.05.2026 10:00");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        btnSacuvaj.setText("Sačuvaj termin");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel6.setText("Popust:");

        jLabel8.setText("Ukupan iznos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatumVreme)
                            .addComponent(txtIznosBezPopusta)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtPopust)
                            .addComponent(txtUkupanIznos)
                            .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIznosBezPopusta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jMenu6.setText("Pacijent");

        miNoviPacijent.setText("Novi pacijent");
        miNoviPacijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviPacijentActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviPacijent);

        miPretragaPacijenta.setText("Pretraga pacijenta");
        miPretragaPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaPacijentaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaPacijenta);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Usluga");

        miNovaUsluga.setText("Nova usluga");
        miNovaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaUslugaActionPerformed(evt);
            }
        });
        jMenu8.add(miNovaUsluga);

        miPretragaUsluge.setText("Pretraga usluge");
        miPretragaUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaUslugeActionPerformed(evt);
            }
        });
        jMenu8.add(miPretragaUsluge);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Termin");

        miPretragaTermina.setText("Pretraga termina");
        miPretragaTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaTerminaActionPerformed(evt);
            }
        });
        jMenu9.add(miPretragaTermina);

        jMenuBar1.add(jMenu9);

        jMenu7.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu7.add(miOdjava);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUlogovani)
                        .addGap(0, 700, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviPacijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviPacijentActionPerformed
        new FormNoviPacijent(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviPacijentActionPerformed

    private void miPretragaPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaPacijentaActionPerformed
        new FormPretragaPacijenta(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaPacijentaActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().logout(ulogovani);
                new LoginForma().setVisible(true);
                Session.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNovaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaUslugaActionPerformed
        new FormNovaUsluga(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaUslugaActionPerformed

    private void miPretragaUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaUslugeActionPerformed
        new FormPretragaUsluge(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaUslugeActionPerformed

    private void miPretragaTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaTerminaActionPerformed
        new FormPretragaTermina(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaTerminaActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed

        Usluga u = (Usluga) cmbUsluga.getSelectedItem();
        String napomena = txtNapomena.getText();

        StavkaTermina st = new StavkaTermina(null, -1, u.getCena(), napomena, u);

        TableModelStavkeTermina tm = (TableModelStavkeTermina) tblStavke.getModel();

        if (tm.postojiUsluga(u)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli ovu uslugu!");
            return;
        }

        tm.dodajStavku(st);

        iznosBezPopusta = tm.vratiUkupanIznos();
        txtIznosBezPopusta.setText(iznosBezPopusta + "din");

        if (txtIznosBezPopusta.getText().isEmpty()) {
            return;
        }

        if (pacijent.getKategorija().getNaziv().equals("Standardni pacijent")) {
            popust = 0;
            txtPopust.setText("0%");
        }
        if (pacijent.getKategorija().getNaziv().equals("Student")) {
            popust = 10;
            txtPopust.setText("10%");
        }
        if (pacijent.getKategorija().getNaziv().equals("Penzioner")) {
            popust = 20;
            txtPopust.setText("20%");
        }

        txtUkupanIznos.setText(iznosBezPopusta * (1 - (popust / 100)) + "din");
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeTermina tm = (TableModelStavkeTermina) tblStavke.getModel();
            tm.obrisiStavku(row);

            iznosBezPopusta = tm.vratiUkupanIznos();
            txtIznosBezPopusta.setText(String.valueOf(iznosBezPopusta) + "din");

            if (txtIznosBezPopusta.getText().isEmpty()) {
                return;
            }

            if (pacijent.getKategorija().getNaziv().equals("Standardni pacijent")) {
                popust = 0;
                txtPopust.setText("0%");
            }
            if (pacijent.getKategorija().getNaziv().equals("Student")) {
                popust = 10;
                txtPopust.setText("10%");
            }
            if (pacijent.getKategorija().getNaziv().equals("Penzioner")) {
                popust = 20;
                txtPopust.setText("20%");
            }

            txtUkupanIznos.setText(iznosBezPopusta * (1 - (popust / 100)) + "din");
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            if (txtDatumVreme.getText().isEmpty() || txtOpis.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti datum pocetka i opis!");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            Date datumVremePocetka;
            
            try {
                 datumVremePocetka = sdf.parse(txtDatumVreme.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                        "Sistem ne može da kreira termin.", 
                        "Greška", 
                        JOptionPane.ERROR_MESSAGE);
                return;
            }      
            
            String opis = txtOpis.getText();

            TableModelStavkeTermina tm = (TableModelStavkeTermina) tblStavke.getModel();

            Termin termin = new Termin(null, datumVremePocetka, opis, iznosBezPopusta,
                    popust, iznosBezPopusta * (1 - (popust / 100)),
                    pacijent, ulogovani, tm.getLista());
            
            
            ClientController.getInstance().addTermin(termin);      
            
            txtDatumVreme.setText("");
            txtOpis.setText("");
            txtIznosBezPopusta.setText("");
            txtNapomena.setText("");
            iznosBezPopusta = 0;
            tm.getLista().clear();
            tm.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio termin.", "Message", 
                                JOptionPane.INFORMATION_MESSAGE);
            
            

        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti termin.", "Greška", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void cmbPacijentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPacijentItemStateChanged
        if (cmbPacijent.getSelectedItem() != null) {

            pacijent = (Pacijent) cmbPacijent.getSelectedItem();

            if (txtIznosBezPopusta.getText().isEmpty()) {
                return;
            }

            if (pacijent.getKategorija().getNaziv().equals("Standardni pacijent")) {
                popust = 0;
                txtPopust.setText("0%");
            }
            if (pacijent.getKategorija().getNaziv().equals("Student")) {
                popust = 10;
                txtPopust.setText("10%");
            }
            if (pacijent.getKategorija().getNaziv().equals("Penzioner")) {
                popust = 20;
                txtPopust.setText("20%");
            }

            txtUkupanIznos.setText(iznosBezPopusta * (1 - (popust / 100)) + "din");
        }
    }//GEN-LAST:event_cmbPacijentItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbPacijent;
    private javax.swing.JComboBox cmbUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNovaUsluga;
    private javax.swing.JMenuItem miNoviPacijent;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaPacijenta;
    private javax.swing.JMenuItem miPretragaTermina;
    private javax.swing.JMenuItem miPretragaUsluge;
    private javax.swing.JTable tblStavke;
    private javax.swing.JFormattedTextField txtDatumVreme;
    private javax.swing.JTextField txtIznosBezPopusta;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    public void popuniUsluge() {
        try {
            ArrayList<Usluga> usluge = ClientController.getInstance().getAllUsluga();

            cmbUsluga.removeAllItems();

            for (Usluga usluga : usluge) {
                cmbUsluga.addItem(usluga);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniPacijente() {
        try {
            ArrayList<Pacijent> pacijenti = ClientController.getInstance().getAllPacijent();

            cmbPacijent.removeAllItems();

            for (Pacijent pacijent1 : pacijenti) {
                cmbPacijent.addItem(pacijent1);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
